version: 2

sources:
  - name: raw_data
    description: "Raw data for NYC taxi rides"
    database: "datawarehousing-dbt" #project ID
    schema: "nyctaxi"
    tables:
      - name: "yellow_tripdata"
      - name: "green_tripdata"